# Generated by Django 4.0.4 on 2022-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=200)),
                ('owned', models.BooleanField(verbose_name='Owned')),
                ('grailed', models.BooleanField(verbose_name='Grailed')),
                ('quantity_owned', models.IntegerField(verbose_name=0)),
                ('price_history', models.JSONField(blank=True, default=list, null=True)),
                ('date_obtained', models.DateTimeField()),
                ('quality', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
