# Generated by Django 4.0.4 on 2022-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterball_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncard',
            name='quantity_owned',
            field=models.IntegerField(default=0, verbose_name='Quantity Owned'),
        ),
    ]
